### ISSUE TITLE
Clone Repository 질문..

### ISSUE THREAD

**Issue by DeukHan** [dev-heeseok/health-record-client#2]
health-recode-client를 fork해서 health-recode-client-deukhan으로 만들었습니다.
 그 이후에 health-recode-client-deukhan에서 Git 리포지토리 복제를 통해 연동하려고 했는데
아래와 같은 에러가 발생하면서 실패합니다
![image](https://user-images.githubusercontent.com/104338516/172392123-fc1a309b-c854-4891-9c66-2f35e0f83f65.png)
![image](https://user-images.githubusercontent.com/104338516/172392649-de150fee-32d9-486b-bb6b-1cbc1cd28b13.png)

뭐가 잘못된 걸까요..??
@dev-heeseok @kimkmin357

**Comment by DeukHan** [comment]
![image](https://user-images.githubusercontent.com/104338516/172396529-3dd525a5-31d1-4d11-84f1-37ff6c38b3b1.png)
git lfs(Large File Storage)때문에 그런거 처럼 보이는데 어떻게 해야 하나요?

**Comment by dev-heeseok** [comment]
@DeukHan 
LFS 오류가 맞는것 같아요. 검색해 보니깐 LFS 를 재설치하니깐 괜찮다는 내용이 있어서 재설치를 해보는걸 추천 드립니다.

```sh
// repository 로 이동 후 아래의 명령어를 실행 하면 됩니다.

// LFS 설치
git lfs uninstall
// LFS 설치
git lfs install
```

**Comment by DeukHan** [comment]
@dev-heeseok 
맥북은 뭔가 좀 다른가 봅니다...ㅜㅜ
잘 모르겠지만 install을 새로 해주니까 잘 됐습니다!!
감사합니다!
1. git-lfs를 설치해 준다. brew install git-lfs 명령어를 통해 설치해준다.
2. Project 폴더로 이동하여 .git 있는 부분에서 git-lfs install 명령어로 설치해준다.
